// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using achappey.ChatGPTeams.Database;

#nullable disable

namespace achappey.ChatGPTeams.Database.Migrations
{
    [DbContext(typeof(ChatGPTeamsContext))]
    [Migration("20230904063017_RelationBugfixes")]
    partial class RelationBugfixes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AssistantFunction", b =>
                {
                    b.Property<int>("AssistantsId")
                        .HasColumnType("int");

                    b.Property<string>("FunctionsId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("AssistantsId", "FunctionsId");

                    b.HasIndex("FunctionsId");

                    b.ToTable("AssistantFunction");
                });

            modelBuilder.Entity("AssistantResource", b =>
                {
                    b.Property<int>("AssistantsId")
                        .HasColumnType("int");

                    b.Property<int>("ResourcesId")
                        .HasColumnType("int");

                    b.HasKey("AssistantsId", "ResourcesId");

                    b.HasIndex("ResourcesId");

                    b.ToTable("AssistantResource");
                });

            modelBuilder.Entity("ConversationFunction", b =>
                {
                    b.Property<string>("ConversationsId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FunctionsId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ConversationsId", "FunctionsId");

                    b.HasIndex("FunctionsId");

                    b.ToTable("ConversationFunction");
                });

            modelBuilder.Entity("ConversationResource", b =>
                {
                    b.Property<string>("ConversationsId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ResourcesId")
                        .HasColumnType("int");

                    b.HasKey("ConversationsId", "ResourcesId");

                    b.HasIndex("ResourcesId");

                    b.ToTable("ConversationResource");
                });

            modelBuilder.Entity("FunctionPrompt", b =>
                {
                    b.Property<string>("FunctionsId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("PromptsId")
                        .HasColumnType("int");

                    b.HasKey("FunctionsId", "PromptsId");

                    b.HasIndex("PromptsId");

                    b.ToTable("FunctionPrompt");
                });

            modelBuilder.Entity("achappey.ChatGPTeams.Database.Models.Assistant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<int>("ModelId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OwnerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Prompt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Temperature")
                        .HasColumnType("real");

                    b.Property<int>("Visibility")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("ModelId");

                    b.HasIndex("OwnerId");

                    b.ToTable("Assistants");
                });

            modelBuilder.Entity("achappey.ChatGPTeams.Database.Models.Conversation", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("AssistantId")
                        .HasColumnType("int");

                    b.Property<int>("ChatType")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("CutOff")
                        .HasColumnType("datetimeoffset");

                    b.Property<float>("Temperature")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("AssistantId");

                    b.ToTable("Conversations");
                });

            modelBuilder.Entity("achappey.ChatGPTeams.Database.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("achappey.ChatGPTeams.Database.Models.Function", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.ToTable("Functions");
                });

            modelBuilder.Entity("achappey.ChatGPTeams.Database.Models.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConversationId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset?>("Created")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("FunctionCall")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("TeamsId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("achappey.ChatGPTeams.Database.Models.Model", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MaxTokenSize")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Model");
                });

            modelBuilder.Entity("achappey.ChatGPTeams.Database.Models.Prompt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssistantId")
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Visibility")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AssistantId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("OwnerId");

                    b.ToTable("Prompts");
                });

            modelBuilder.Entity("achappey.ChatGPTeams.Database.Models.Resource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Resources");
                });

            modelBuilder.Entity("achappey.ChatGPTeams.Database.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AssistantFunction", b =>
                {
                    b.HasOne("achappey.ChatGPTeams.Database.Models.Assistant", null)
                        .WithMany()
                        .HasForeignKey("AssistantsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("achappey.ChatGPTeams.Database.Models.Function", null)
                        .WithMany()
                        .HasForeignKey("FunctionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AssistantResource", b =>
                {
                    b.HasOne("achappey.ChatGPTeams.Database.Models.Assistant", null)
                        .WithMany()
                        .HasForeignKey("AssistantsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("achappey.ChatGPTeams.Database.Models.Resource", null)
                        .WithMany()
                        .HasForeignKey("ResourcesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ConversationFunction", b =>
                {
                    b.HasOne("achappey.ChatGPTeams.Database.Models.Conversation", null)
                        .WithMany()
                        .HasForeignKey("ConversationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("achappey.ChatGPTeams.Database.Models.Function", null)
                        .WithMany()
                        .HasForeignKey("FunctionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ConversationResource", b =>
                {
                    b.HasOne("achappey.ChatGPTeams.Database.Models.Conversation", null)
                        .WithMany()
                        .HasForeignKey("ConversationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("achappey.ChatGPTeams.Database.Models.Resource", null)
                        .WithMany()
                        .HasForeignKey("ResourcesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FunctionPrompt", b =>
                {
                    b.HasOne("achappey.ChatGPTeams.Database.Models.Function", null)
                        .WithMany()
                        .HasForeignKey("FunctionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("achappey.ChatGPTeams.Database.Models.Prompt", null)
                        .WithMany()
                        .HasForeignKey("PromptsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("achappey.ChatGPTeams.Database.Models.Assistant", b =>
                {
                    b.HasOne("achappey.ChatGPTeams.Database.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId");

                    b.HasOne("achappey.ChatGPTeams.Database.Models.Model", "Model")
                        .WithMany()
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("achappey.ChatGPTeams.Database.Models.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId");

                    b.Navigation("Department");

                    b.Navigation("Model");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("achappey.ChatGPTeams.Database.Models.Conversation", b =>
                {
                    b.HasOne("achappey.ChatGPTeams.Database.Models.Assistant", "Assistant")
                        .WithMany("Conversations")
                        .HasForeignKey("AssistantId");

                    b.Navigation("Assistant");
                });

            modelBuilder.Entity("achappey.ChatGPTeams.Database.Models.Message", b =>
                {
                    b.HasOne("achappey.ChatGPTeams.Database.Models.Conversation", "Conversation")
                        .WithMany()
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("achappey.ChatGPTeams.Database.Models.Prompt", b =>
                {
                    b.HasOne("achappey.ChatGPTeams.Database.Models.Assistant", "Assistant")
                        .WithMany()
                        .HasForeignKey("AssistantId");

                    b.HasOne("achappey.ChatGPTeams.Database.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId");

                    b.HasOne("achappey.ChatGPTeams.Database.Models.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assistant");

                    b.Navigation("Department");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("achappey.ChatGPTeams.Database.Models.Assistant", b =>
                {
                    b.Navigation("Conversations");
                });
#pragma warning restore 612, 618
        }
    }
}
